### PR TITLE
Implement the remaining SMG entities (HV and PT Edges)

### PR DESCRIPTION
**Pull request by petr-muller**

### CODE REVIEW

**Comment by michkot** [comment]
I would like to ask about "-fsanitize=address -fsanitize=leak -fsanitize=undefined" g++ switches - what is the motivation for this change [I don't know gcc so well], also with -Wall and -pedantic, there is a lot of warnings in this code, as you can see here: https://travis-ci.org/michkot/smg3/builds/100169012

**Comment by petr-muller** [comment]
Sanitizers: It's a compiler infrastructure helping testing - the executable code is instrumented with runtime checks against an array of possible errors with memory (AddressSanitizer), memory leaks (LeakSanitizer) and other undefined behavior (UBSanitizer). Think of it as compiled-in, much more efficient and more universal Valgrind. Of course this should be off in production builds, but I did not want to invest time into that as the current makefiles will be replaced by something saner anyway.

Example:

```
$ cat oob.c 
int main() {
  int array[8];
  array[8] = 0;
  return 0;
}
$ gcc oob.c -fsanitize=undefined ; ./a.out 
oob.c:3:8: runtime error: index 8 out of bounds for type 'int [8]'
oob.c:3:12: runtime error: store to address 0x7fffe9cdf1b0 with insufficient space for an object of type 'int'
0x7fffe9cdf1b0: note: pointer points here
 00 00 00 00  50 07 40 00 00 00 00 00  80 d5 9c d1 fe 7e 00 00  18 d3 fa d1 fe 7e 00 00  98 f2 cd e9
```

See more:
- http://developerblog.redhat.com/2014/10/16/gcc-undefined-behavior-sanitizer-ubsan/
- http://developerblog.redhat.com/2014/12/02/address-and-thread-sanitizers-gcc/

**Comment by petr-muller** [comment]
For -Wall -pedantic, I think it is a good idea to switch them on (and also use -Werror) and fix the issued. Thanks for the hint, I'll get back with the necessary changes.

**Comment by petr-muller** [comment]
Actually the compile is (by sheer luck :) clean under -Wall -pedantic. All those warning are -Wextra or something even weaker. Do we generally want -Wextra (I think we do)?

**Comment by michkot** [comment]
I am for -Wextra (sorry for the mystification). 
Also, an excerpt from PP (in czech) about the (only/most common) problem reported:

> nema smysl psat
> const T funkce();
> ^^^^^ to const je naprosto zbytecne (pokut T neni reference/uk, tedy T&/*)
> Reseni: zrusit to **prvni** const u metod s tim varovanim.

eg. remove all the front **const** from functions returning value types

**Comment by petr-muller** [comment]
Sure, it's fixed already in  997a666

**Pull request merged**
